### ISSUE TITLE
apex --version/-V do not work

### ISSUE THREAD

**Issue by glkz** [apex/apex#101]
After cobra change, both ```apex -V``` and ```apex --version``` do not seem to work.

**Comment by pilwon** [comment]
@glkz Confirmed this. Working on a fix now.

**Comment by pilwon** [comment]
@tj @mthenw Looks like there isn't a clean way to print version with persistent flag. So I created `apex version` to handle this case instead. Are you guys cool with the change? (PR #103)

**Comment by glkz** [comment]
@pilwon #103 works only in a project directory.

I think, the real problem is in the [```rootCmd```](https://github.com/apex/apex/blob/master/cmd/apex/apex.go#L9).

```pv.PreRun``` assumes that all the commands will run in a project scope which is not always true. IMO, we should set ```PersistentPreRun: pv.PreRun``` in individual project-level commands. 

After that, ```apex version``` command will be fine. Also, the option version (```-V``` or ```--version```) can be implemented in ```rootCmd.Run```.

**Comment by pilwon** [comment]
> ```pv.PreRun``` assumes that all the commands will run in a project scope which is not always true. IMO, we should set ```PersistentPreRun: pv.PreRun``` in individual project-level commands.

We're aware of this issue and PR #104 will take care of it. All commands except `version` and `wiki` are meant to be run at the project root, commands inheriting `PersistentPreRun` from the root command feels more natural to me.

> the option version (```-V``` or ```--version```) can be implemented in ```rootCmd.Run```.

This unfortunately doesn't work because `rootCmd.Run` will not run for non-root commands. This can be implemented in `rootCmd.PersistentPreRun` though but this is rather hackish solution than having a clean, dedicated version command as in PR #103.
