### ISSUE TITLE
Allow multiple IAM accounts in project.json

### ISSUE THREAD

**Issue by robzienert** [apex/apex#109]
For larger orgs it's fairly common to have a different AWS account per environment, which typically means different IAM roles. It would be nice to either:

1. Add an arg to override what path to load project.json at

`$ apex -p project-staging.json`

2. Add templating into the project.json that let's you render values from the ENV:

```
{
  ...
  "role": "arn:aws:iam::{{.AWSAccountID}}:role/lambda"
}
```

**Comment by robzienert** [comment]
Happy to do the legwork, but want to know what direction people think is best.

**Comment by tj** [comment]
Ah yep, totally. We still need to define future-proofing for the config but I completely agree that this needs to get integrated in some form. #59 is the issue regarding config in general. I think having first-class environments would be nice since it's something everyone deals with. That would give us the ability to have some form of env-switcher too.

**Comment by DavidTPate** [comment]
Yeah, first class environments would definitely be preferred for me. That's also how most things tend to implement it in regards to AWS (take the AWS CLI for example, you just say `--profile prod` or `--profile staging`)

**Comment by analytically** [comment]
+1

**Comment by tj** [comment]
Suppose we can close this for #178
