### ISSUE TITLE
Use build output as Lambda function

### ISSUE THREAD

**Issue by plukevdh** [apex/apex#168]
This may be an edge case specific to us, but Apex is something we're considering over [a tool](articulate/jarbs) we've built internally for many of the same purposes accomplished here.

We've preferred to organize our code (primarily JS) with deeper hierarchies than a simple `index.js` file. Something like:

```
src
├── index.js
├── lib
│   ├── addMeta.js
│   ├── buildFlow.js
│   ├── helpers.js
│   ├── loadEnv.js
│   ├── mailer
│   │   ├── addTemplate.js
│   │   ├── mailerFlow.js
│   │   ├── updateUrlValue.js
│   │   └── validateInput.js
│   ├── removeMeta.js
│   ├── shouldProcess.js
│   └── sns
│       ├── classify.js
│       ├── unwrapEvent.js
└── package.json
```

We typically prefer to keep one function to a file and use `import`/`require` to build out the dependency trees. With that said, the build/clean step much harder with Apex when using for things like building larger function structures when combined with, say, transpiling ES6 -> ES5 or Coffee -> JS. It'd be useful to be able to specify a "package from this directory on build" flag, that way we can simply do:

```json
{
  "artifacts": "dest",
  "hooks": { 
    "build": "babel --out-dir ./dest ./src",
    "clean": "rm ./dest"
  }
}
```

Where "artifacts" is the directory to be packaged into the `.zip` archive for upload. Does this seem too edge case for what the goals of Apex are?

**Comment by plukevdh** [comment]
Willing to put down code to help with this feature if it seems like a reasonable feature request. I just wanted to ensure this is a valid use case for Apex

**Comment by tj** [comment]
Hmm yea I think this makes sense for most cases, basically the inverse of .apexignore. For Go you could just specify the "main" output or main + assets if you have anything that wasn't inlined. I guess the use-case here is slightly different since it's a target directory but maybe we could change the default Go stuff to produce `./build/main` and `rm -fr build`. I'm :+1:, we just need to figure out what this looks like.

Part of me does like that you know what's in the dir is available to you in Lambda. I guess even in the node/transpiling case you don't actually "see" the build output, even if it's spewed all over that directory, it's removed on "clean" anyway. So in that case you could just `babel --out-dir . src`.

Or if that's too nasty you could `babel --out-dir ./build ./src` with:

```json
{
  "handler": "build/index.handle"
}
```

I haven't tried handler with a dir in the name but I'm assuming it works. At least that wouldn't require any Apex changes, plus if we support babel out of the box (I'd like to) the user doesn't have to get all confused by these settings.

**Comment by plukevdh** [comment]
The problem I've had with doing a `babel --out-dir . src` is when you have to deal with prod vs. dev dependencies (i.e. babel-cli vs. just the runtime). It's hard to separate dependencies getting mixed up in something like a `node_modules` dir without a separate "clean deps for deploy" step. If you build in two separate dirs (or copy to a new dir, _then_ build it locally in that dir) it keeps the source better isolated from the artifacts. 

The approach we've taken thus far has been to still to give the user control over the build step (similar to your hooks), but to assume all build commands would be run against (or from within) the `build` dir. 

I think you're correct in saying the build hook will work with dirs in Apex as-is. The only change that would be needed I think is the "package this dir" rather than a single file. I'll test the idea of building to the CWD and using `.apexignore` and report back.

**Comment by tj** [comment]
Sounds good! So far I'm seeing tradeoffs either way, the downside of the current way is having to .apexignore the input source, and the downside of a build dir is you'd have to move put your non-source assets in there. I can't think of a clear winner ATM.

**Comment by matthew-andrews** [comment]
Could this achieved simply by allow you to (optionally) specify a `.zip` file to `apex deploy [functionname]` that way, when you wanted to, you could take responsibility for creating that artefact.

So something like this might work:-
```shell
apex build myfunc > tmp-build.zip
apex deploy myfunc --zip tmp-build.zip
rm tmp-build.zip
```

[`apex deploy` would **still** read all the config options, etc from the normal place (instead of from within the zip).]

Just an idea…

**Comment by tj** [comment]
Specifying the directory is pretty much the same as specifying the zip, just one less step for the user to worry about

**Comment by matthew-andrews** [comment]
@tj Good point.

@plukevdh One way to fix the devDeps problem is by having two `package.json` files.  One in the root of the project (devDeps only) and one in each Lambda function (deps only) and running `npm install` twice.

E.g. https://github.com/Financial-Times/next-url-management-api/pull/42/files

Alternatively I wrote [this script](https://github.com/matthew-andrews/haikro/blob/master/lib/build.js#L106-L138) that will extract the **dependencies** from a `node_modules` folder (skipping, without deleting, the devDependencies).  I've been meaning to extract that into a reusable module on its own for a while…

**Comment by mthenw** [comment]
Tough call. Assuming that `"handler": "build/index.handle"` works fine I'm not sure about changing anything ATM. Users (using build hook) can copy whatever files they want to build directory and then use them as they would be in `.` inside Lambda function.

Apex is great because it's simple ("we will zip all files in functions dir. use .apexignore to exclude some of them.")

**Comment by tj** [comment]
Yea I like that it's simple there too, just need something reasonable to recommend to people or some out of the box solution for interpreted languages.

**Comment by plukevdh** [comment]
Having the default be `build/index.js`is super reasonable, though I think, since you _can_ configure the handler function in the Lambda SDK, it's worth making that an option somewhere down the road as well. Probably via the `function.json` file. But thats something we can worry about outside of this issue. I think as soon as you assume for development, all resources are local within a `src` dir and all resource for deployment are _also_ local in a `build` dir, then you're really just needing to worry about your CWD given what type of operation you're performing (transpiling, local runtime, dependency management, etc). IMO,  Once you separate "built and deployable" resources from "dev-time" resources, the operations performed between those two get a lot cleaner and more isolated.

**Comment by tj** [comment]
Yeah distinct build dirs is nice in that sense, for Go it's pretty much irrelevant unless you don't want to inline some data, then the CWD does matter.

I'm going to move this to v0.7.0 so we have a bit more time to hash out the details, definitely need to think about it more and see if we can come up with a solution that is simple for all cases.

**Comment by tj** [comment]
Using webpack or browserify as shown in ./_examples fixes this issue.
