### ISSUE TITLE
Multi-function projects

### ISSUE THREAD

**Issue by mthenw** [apex/apex#18]
Hi TJ,

what is desired scope of this tool? Are you planning to support API Gateway? I don't like `serverless` because it's too complicated. Apex is much cleaner (it's obvious because it's smaller, but based on my experience with your libs/tools/frameworks it will stay simple :)). I know that this is stated as a difference between apex and serverless but are you planning to support multi-function project?

**Comment by tj** [comment]
I'd definitely like to keep it simple at its core. I really believe Terraform is better for managing most things, but since TF doesn't support API gateway and that's a natural fit here, it's pretty likely to get in! I just need to prep a few other things before I can work on that.

I'd like apex(1) to be flexible enough that multi-function can be easily supported on top of the single-function oriented commands. Possible as part of apex(1) or as a separate project. I'll have to see how my own work turns out but I think in most cases there's still a 1:1 repo-per-function, mainly for CI and continuous delivery etc.

Let me know if you think otherwise! Some more input there would be helpful, I went back and forth on that a bit but settled with simple.

**Comment by tj** [comment]
Actually thinking about it a bit more now I think it might make sense to have some multi-function support. For my use-cases I don't really need it (yet) but I could see how people might have a function per API Gateway resource and want to maintain those in a single API repo.

**Comment by mthenw** [comment]
> I really believe Terraform is better for managing most things

Same here. Eventually, Terraform will get API Gateway support, but still, I would add it to `apex` to make it more user friendly (there is always 1-to-1 link between API Gateway res and Lambda func).

> Actually thinking about it a bit more now I think it might make sense to have some multi-function support. For my use-cases I don't really need it (yet) but I could see how people might have a function per API Gateway resource and want to maintain those in a single API repo.

This is a use case that I've been thinking about.

Generally I think that in terms of structure there is a few ways to support multi-function projects:

0. The one that you proposed with `./function`. (personally I don't like if framework expects from me to provide some specific folder structure)
1. __One function per folder__ (stored in index.<ext> by default) and mandatory `lambda.json` so apex will be able to determine if there is anything to deploy.
2. __Function stored in <name>.lambda.<ext>__ (config could be stored in <name>.lambda.json). It would solve the problem with having only one function in dir (I'm not sure if it's a problem though). Also, I'm not sure but probably config could be not mandatory (some values can be inherited from root level lambda.json(?)).

The other problem with supporting multi-function is deploy. As there is no one place with state it's impossible to determine which function has to be updated. No idea how to solve this.

**Comment by tj** [comment]
Using lambda.json to declare them (per dir) is probably what I'd vote for. I do sort of like convention > config as well simply because all projects look alike, which can be really nice for a community. After all that's the main thing I like about Go haha everything looks the same.

I haven't thought about it much yet but we should be fine to just use the checksum like Apex currently does for a single deploy (it no-ops if nothing changed).

**Comment by mthenw** [comment]
> I haven't thought about it much yet but we should be fine to just use the checksum like Apex currently does for a single deploy (it no-ops if nothing changed).

Yup, make sense. I've not noticed that checksum check before.

**Comment by tj** [comment]
It's a little slow to produce the zip first just for that. Guess we'll see haha

**Comment by tj** [comment]
Thinking ahead a bit, maybe this command structure, since everything is "package" based, vs serverless's three different types (project, function etc). Part of me wants to lean towards convention > config, mostly because I think vendoring is the simplest way to manage deps and prevent weird shit with people injecting code etc. 

```
# install log-collector to ./vendor/log-collector
$ apex install apex/log-collector

# deploys all functions & resources
$ apex deploy

# deploys function or resources in ./vendor/{name} or ./lambda/{name}
$ apex deploy <name>

# deploys configuration changes only
$ apex deploy config
$ apex deploy config <name>

# deploys resources only
$ apex deploy resources
$ apex deploy resources <name>

# delete function 
$ apex delete <name>
```

Let me know what you think!

**Comment by mthenw** [comment]
:+1: 

Two things:

1. I'm not sure about `./vendor` and `resource`. I mean it's the same but have different names. Maybe `./package` and `package` or `./deps` and 'dep`? Or maybe it's just me :)

2. `apex deploy <name>` might be confusing if user will start adding functions with the same name as resources and won't notice that. I think it would be better to leave it only for functions.

You probably missed that `apex delete` should delete everything.

**Comment by tj** [comment]
Starting to think we should pass paths so vendor stuff can be differentiated etc, maybe defaulting to ./functions/<arg>. Definitely need some kind of differentiator there.

```
# delete ./functions/foo
$ apex delete foo

# delete ./vendor/apex-log-collector and all its functions
$ apex delete foo vendor/apex-log-collector

# delete ./vendor/apex-log-collector's foo function
$ apex delete foo vendor/apex-log-collector/functions/foo
```

**Comment by mthenw** [comment]
I would start with `apex delete -C vendor/something foo` and after some time would add something vendor specific, if necessary.

**Comment by mthenw** [comment]
What do you think about prefixing functions names with project name? Right now there is no way to deploy two different project which shares function names.

**Comment by tj** [comment]
Hmm yeah good call, sounds fine to me!

**Comment by tj** [comment]
forgot to close this
