### ISSUE TITLE
Google Cloud Functions support

### ISSUE THREAD

**Issue by mthenw** [apex/apex#232]
https://cloud.google.com/functions/docs

Sounds nice to support both AWS and Google. Probably far from implementation but still we can consider that.

**Comment by tj** [comment]
haha damnn! nice, could be interesting

**Comment by binoculars** [comment]
Does anyone actually have access to Google Cloud Functions? I requested to be whitelisted by filling out the form, but have not gotten a response yet. It's been a while--at least a week or two. It's in alpha right now, so who knows if they are approving these or not.

**Comment by mthenw** [comment]
@binoculars I also requested to be whitelisted and I also haven't got access yet.

**Comment by tmaiaroto** [comment]
I do (if no one else has access by now). Let me know if I can help (flag me down on Slack)...though be aware Google has some pretty strict language about sharing info about it (not sure how they can prevent people from sharing info -- but I wouldn't expect too many blog posts about it for now). GCF only has Node.js support for now.

**Comment by jthomas** [comment]
There's now [OpenWhisk](https://github.com/openwhisk/openwhisk) as well.
Does the Apex project think supporting other platforms would be a good addition?
If so, I can volunteer to help out with the OpenWhisk support.

Now sure how coupled the codebase is to AWS and how easy it would be to support both backends.

**Comment by mthenw** [comment]
@jthomas right now is quite coupled, it would require some work to abstract provider (AWS Lambda, GCF, OpenWhisk) level. Let's see if OpenWhisk will get enough popularity.

**Comment by tmaiaroto** [comment]
There's also Iron.io of course, which has been around for a good while.
There's plenty of places these functions "can" run. For a variety of
reasons too. I was even asking about AWS ECS Tasks in Slack and if they fit.

Though I think it's OK to keep it limited. Especially for now, while these
services are still changing and while Apex itself is too.

Personally, I would certainly think about supporting many providers. They
seem to be shaping up to satisfy different use cases in a cloud
architecture.

In fact, at some point, I think multiple providers will become a critical
feature for a microservices framework. On top of that, monitoring/metrics
between and across the cloud providers.

I suspect mix and match providers (or at least services) will become a
trend for microservices and serverless in the very near future.

Anyway. Just my two cents and predictions for this space.

**Comment by mthenw** [comment]
Now Azure. https://azure.microsoft.com/en-us/services/functions/

**Comment by jasonpolites** [comment]
Hi guys.  I'm the PM for Google Cloud Functions.  If you ping me directly (jplts_at_google.com) I will make sure you're added to the Alpha

**Comment by tj** [comment]
@mthenw mentioned he has access. I'm not personally too interested since it just increases our maintenance burden, I'm only using AWS Lambda in practice, but compat for all of them some day would be pretty cool

**Comment by jasonpolites** [comment]
kk no problem.  @mthenw LMK if you have any questions etc.

Cheers,

Jason.

**Comment by mthenw** [comment]
@jasonpolites I planning to spend some time on validating Apex support for gcloud functions. Are you planning to add Functions support to https://godoc.org/google.golang.org/cloud anytime soon?

**Comment by tmaiaroto** [comment]
I'm more interested in GCF after recent changes there in the alpha. Which I won't discuss here, don't worry Jason =)

**Comment by jasonpolites** [comment]
@mthenw Right now we're focussed on getting to public beta.  There's a tendency sometimes to be "distracted" by adding lots of features and the expense of reliability, scalability, security etc.  That said, we definitely recognize that Javascript is not the end state.  Java/Python/Go etc are all on the radar (both in terms of support within the Function, and from clients in these languages).  Of course you can invoke a function from many places, and many languages today (via [HTTP](https://godoc.org/google.golang.org/cloud#WithBaseHTTP) or [Pub/Sub](https://godoc.org/google.golang.org/cloud/pubsub)).

**Comment by mthenw** [comment]
@jasonpolites probably I wasn't clear enough :) My question was about support in SDK. I would like to create/delete/invokee function using Go SDK.

**Comment by tj** [comment]
Shameless plug (◕‿◕) in case Google is interested in supporting our stuff :D https://opencollective.com/apex. Compat layer would take a bit of work, and we'd need parity so they at least all have logging etc but it would be pretty neat if people had less lock-in with all these options coming out

**Comment by tmaiaroto** [comment]
I don't think there'd be good parity right now, based on what I've seen, but GCFs is moving fast.

**Comment by tj** [comment]
Stuff like `apex metrics` we can do without I think, pretty much just need deploy/rollback/logs, but I haven't even looked at it yet haha maybe it has all that

**Comment by jasonpolites** [comment]
So.. we *do* have an API for deployment, but it's not particularly well documented right now.  We'll fix that and ultimately I think it makes sense that we'd have dedicated client libraries in various languages.  Logging is done through Cloud Logging (now called Stackdriver Logging), which does have a golang client.  Rollback (versioning etc) is not currently provided in the base platform, but we support integration with github and bitbucket so you can affect a "rollback" by simply re-deploying an earlier commit.

One small note though.  Cloud Functions does not have an ambition to be an *equivalent* to alternate solutions like Lambda or Azure Functions per se.  Its ambition is to follow the needs of the customer in creating the *right* solution for serverless applications and microservices; which may mean it's necessarily different in some areas from other solutions.  If you want to create a generalization of this across multiple providers (Google, Microsoft, Amazon etc); then the only way you can account for these differences is to have deviation in your solution, or baseline on the lowest common feature-set.  I can't promise that Google Cloud Functions will ever have complete parity with Lambda or Azure Functions because it's not yet clear that anyone has the perfect mix of features.  For example Cloud Functions comes with HTTP invocation out of the box (does not require a separate service); we support deployment from source repos like github and bitbucket (as mentioned) and we have a range of other *different* things coming soon.  We do this because we feel these are features of value to customers, regardless of whether they are similar or dissimilar to anyone else's solution.

**Comment by jasonpolites** [comment]
P.S.  I'll be at the serverless conf in NYC later this month if anyone wants to meet up.

**Comment by tmaiaroto** [comment]
For what it's worth - I find the differences in services great because it just means options when choosing the right tool for the job.

Also worth noting that these are all very new and rapidly changing. Azure for example has no max execution time unlike Lambda. It also has storage persistence...But all of that could change too of course.

Is there a point at which we'll have a bit more clarity and (rough) dependability on the limitations of Google Cloud Functions?

**Comment by tj** [comment]
I agree it wouldn't be good to only support the base set of features. I think we could support the full range as long as omissions are obvious to the user. Definitely opens up a lot more maintenance though, that's my worry. Maybe 'serverless' will do it since they're monetizing, but they're also coupled to CloudFormation so maybe not

**Comment by jasonpolites** [comment]
To your specific question, you'll have more clarity on the first public version when that's released (can't give timelines, but "soon").  However I can give you some guiding principles we're likely to follow:

(note these are merely guidelines, not any promises of actual features ;)

- Cloud Functions themselves are stateless.  This allows us to scale them independent of constraints like location etc.  
- Local storage is ephemeral, but persistent storage is available via other solutions (Datastore, Cloud Storage etc)
- If customers are billed for execution time, we should care how long they execute, but we *should* care about rogue functions stuck in loops that might cost the customer a lot of money
- Customers should not be constrained by what they can run.  If you have a crazy C++ lib that you want to run from your function, you should be able to do that without jumping through a lot of hoops
- Everything should be an API.  You shouldn't be left in a situation where any effort to automate is crippled by needing a human to click a button at some point in the process
- Language is a choice by the developer, not by us.  You should be able to choose whatever language you like (OK.. maybe not Fortran.. but you get the idea)
- A graph of 100's of interconnected, interdependent but loosely coupled functions/services will be a nightmare to trace/debug.  This creates a natural ceiling on complexity.  That's bad.  We should fix that.

**Comment by iNDicat0r** [comment]
GCF is still in alpha, and currently supports javascript only. this is the main limitation since it doesnt allow the dev to be flexible. Golang is developped by google and it sounds crazy that its not supported by default. On the other hand, AWS has offical support for 4 languages + you can run your compiled code or binary file within their infrastructure.

**Comment by tj** [comment]
Oops i should close this anyway. I doubt I'll ever use Google funcs, and I'm generally not a huge fan of mixing providers since they have different semantics, it would get more confusing, like an ORM which doesn't fully take advantage of any database because it's abstracted too much.

**Comment by sourcec0de** [comment]
They just released into beta. Sad to see apex won't support cloud functions.
Great work either way. Thank you.

**Comment by tmaiaroto** [comment]
I was in their alpha and while I did see people getting Golang to work on GCF (and I'll probably experiment a bit more with that), I wasn't so sure the capabilities of GCF. Of course it was alpha then and it's still only beta now, but it doesn't seem as capable as AWS. So it has a long ways to go before it reaches parity which means Apex could very likely have some feature limitations running on GCF.

Aside from that, I'm unsure if they released pricing info publicly or not but that's going to be another thing to consider. I wasn't too sure I loved the pricing model (though there is a free tier). I still see AWS Lambda as the best option for serverless at the moment (though I really like the healthy competition). I've done a more in depth comparison with Azure Functions, but do need to do the same kind of diligence with other providers such as GCF.

So I guess my two cents is that it might be worth revisiting later, but I'd rather see time/effort put into other areas before taking on another provider. That would just increase the technical debt and slow down development to some varying degree.

**Comment by mikeschinkel** [comment]
Any updates on this?

**Comment by brillout** [comment]
>  I doubt I'll ever use Google funcs

@tj why? Anything wrong with Google Cloud Functions?

**Comment by tj** [comment]
@brillout I don't think anything is wrong with them, I couldn't say since I haven't used them, but I use AWS for most things (BigQuery is the only exception right now)

**Comment by Cokemonkey11** [comment]
Is this being revisited? I would like to use GCF with rust, and apex seems like a logical wrapper for doing so.

**Comment by harrisrobin** [comment]
Apologies for the spam, but just wanted to add my support here for GCF.

I'm a huge fan of Apex's products, i use both `up` and `ping`, however I have to admit that i often have GC credits and sometimes using lambda is not an option for me and it really feels like a downgrade to not use `up` or have to use serverless.

🍻
