### ISSUE TITLE
Binary distribution via Homebrew

### ISSUE THREAD

**Issue by mthenw** [apex/apex#252]
It could partly solve https://github.com/apex/apex/issues/199

Thoughts?

**Comment by tj** [comment]
:+1:  might as well as long as it's not annoying to update the version all the time, IIRC that is done manually each time? That script isn't so bad since it installs for osx, but it's the other platforms that are annoying. Ideally We'd at have a script that you can just `curl` and it detects your os / arch

**Comment by tj** [comment]
re #199

**Comment by mthenw** [comment]
> IIRC that is done manually each time?
yeah. but I can take care of that. well I don't like `curl | sh` because of security. Also I (and probably not only I) by default use `brew` to install stuff. 

OK so I will create a formula. We can use it in readme or not :)

**Comment by tj** [comment]
brew does arbitrary stuff too, it _could_ be just as insecure, people can always vet the script first if they're paranoid haha. The manual version thing is my beef with Homebrew, it's almost always out of date

**Comment by mthenw** [comment]
Hmm, that's right, ok, I'm closing this issue for now as we have #199.

**Comment by tj** [comment]
I guess we have `apex upgrade` so even in the outdated case it's not too bad haha, forgot about that

**Comment by mthenw** [comment]
yeah... :)

**Comment by tj** [comment]
That being said I think #199 would be great, any Go program could use it
