### ISSUE TITLE
Rollback command

### ISSUE THREAD

**Issue by tj** [apex/apex#5]
```
$ apex rollback
$ apex rollback --version N
```

**Comment by mthenw** [comment]
I can take care of that. 

Just to make sure. By rollback you mean publishing (after getting function from AWS Lambda) function with version number lower than the current one. Assuming that we have following versions scenerio:

-> $LATEST
-> 10
-> 9
-> 8

`apex rollback`

-> $LATEST
-> 11 (same as 9)
-> 10
-> 9
-> 8


We should also delete v9 and v10 because another rollback will give unexpected result. Same with `--version N` - we should delete all versions between $LATEST and N (including N), right?

**Comment by tj** [comment]
Might be best to use aliases in place of $LATEST, then we can just point to the actual version. I like isolated accounts for envs but maybe just 'current' or 'active'.

Multiple `apex rollback` calls would probably just toggle between the most recent two. 

```
current = 3
versions = 1, 2, 3
```

```
$ apex rollback
current = 2
versions = 1, 2, 3
```

```
$ apex rollback
current = 3
versions = 1, 2, 3
```

That's probably what I would expect at least. We might need another alias then to store the previous. Not a huge deal for now though, even without we can just jump back one that's good enough for now haha. 

Maybe `apex rollback <version>` instead of the flag too

**Comment by mthenw** [comment]
> Might be best to use aliases in place of $LATEST
Yeah, makes more sense. I need to read AWS Lambda docs about aliasing and will be back with PR.
