### ISSUE TITLE
What's the purpose of the Terraform integration?

### ISSUE THREAD

**Issue by dcosson** [apex/apex#523]
Hi, I'm just trying out Apex. First off, it looks like a great framework that ya'll have put a lot of work into, so thanks. I was attracted to it because it mentions integration with Terraform, which I already use quite a bit. 

I'm a little confused though, as soon as I ran `apex init`, apex actually hit the AWS API and created an IAM role & profile, with no option to hook in terraform at all.

So my initial impression is that Apex may sometimes (but not in the case of creating this logs role?) use terraform under the hood to create resources, but as a user that is abstracted from me. I have to completely buy in to the `apex` cli tool for all infrastructure changes (i.e. using `apex infra` to wrap terraform plan & apply). Would you say that's accurate?

I was hoping I could use Apex as a way to organize my lambda functions in dev and generate the Terraform boilerplate for deploying them. I don't want to use `apex infra` to run applies, because I typically have my own wrapper around terraform already that will e.g. switch between environments that live in different aws accounts, make 2FA use a little nicer, or I might be using remote state, or have some other kind of preprocessing step already in place with terraform.  Instead I want Apex to output a terraform module or something, that I could then edit by hand if necessary (e.g. tweak IAM permissions to give access to other resources of mine) and include in my existing terraform configuration.

Is this a use case that you have in mind for Apex? Or is Apex only really meant to support small projects that can commit 100% to the Apex way and have no other infrastructure management tools or anything to hook into?

**Comment by DavidTPate** [comment]
I can't speak to @tj's vision, but I can speak to how Terraform is used in Apex currently.

**apex init**
The command `apex init` uses the AWS SDK to go through and setup roles, an example function, and the other associated pieces.

**Terraform**
Terraform is very loosely integrated into Apex currently (and from my impression for the future as well, so that other tools could be used). You can execute `apex infra [cmd] [args...]` which basically just serves as a wrapper to `terraform [cmd] [args...]`. Under the hood all it is doing is executing your command in Terraform. You could go through and execute in a different environment though such as `apex infra --env staging [cmd] [args...]`.

Besides being able to invoke Terraform through the CLI wrapper you can have `apex` lookup the role that has been created in Terraform to use as the default role for your functions. But you could just manually specify this instead. What it does here is run the `terraform output lambda_function_role_id` which grabs the output value of the name `lambda_function_role_id` which should be the Role's ARN (again this could just be entered manually instead).

**Other tool support**
As I mentioned above, at the end of the day you can manually specify a Role ARN within your project & function configuration so it is pretty opened. For example you could write a straight boto script that sets up your API Gateway, Streams, etc. as the integration is loosely coupled to Terraform.

**How I Use It**
I have a number of Lambda functions spread out over multiple AWS account & multiple environments all of which are utilizing Terraform & Apex and they are used to continually deploy changes as well (making sure that tests pass, and verifying them once deployed).

My project structure looks like the following:

* functions
  * functionA
    * function.test.json - Uses environment variables & special configuration for Test environment (lower provisioning). Specifies a specific Role ARN (can't target multiple Role ARNs from Terraform currently, so it has to be hardcoded).
    * function.stage.json - Same as above
    * function.prod.json - Same as above
* infrastructure
  * base - Terraform module containing configurable parts (to vary environment, tags, account, etc) of how all of the functions in the repo are setup. Contains setup for the functions, what they consume, API gateway, etc.
  * test 
    * main.tf - Pulls in the `base` module above, passes configuration parameters.
    * outputs.tf - Specifies the roles that are to be used for functions and a default one for Apex to use.
    * variables.tf - Specifies specifics that I need for the configuration (such as tags) to enable more variability in targeting deployed functions)
  * stage
    * (same structure as `test` above but different configuration for module)
  * prod
    * (same structure as `test` above but different configuration for module)

From there once I get up to my CI server I run all of my tests, then build my function using [Babel + Webpack](https://github.com/apex/apex/tree/master/_examples/babel-webpack) and run my tests once more against the built function. If everything passes then I run through the following:

1. Check for infrastructure changes to the environment with `apex infra --env test plan`.
2. If there are changes and they aren't destroying things I apply them `apex infra --env test apply`.
3. From there I then deploy the function with `apex deploy --env test`
4. From here my deployment pipeline takes care of migrating changes between my environments by going through the same process as above but for different environments. With external tools checking the APIs & other functionality to make sure the deployment will go well and doesn't need to be rolled back.

There's a few inconveniences that I run into with this current setup.
* My `function.*.json` files need to have the same setup as my function in Terraform so they don't keep overwriting each other (ie. same runtime, timeout, etc).
* I have to hardcode my roles currently so that I can provide different roles to my different functions, there's #503 which would address this.

**Comment by tj** [comment]
I wouldn't say it's catered to small projects, I would say though that it caters to my personal workflow. apex(1) isn't a product, I made it open-source so people could utilize it if they found it useful, so it miiiight not be a great fit for everyone, and it's not trying to be.

If you have a custom Terraform workflow already then for sure it might not be the best, though you could probably ignore `apex infra` all together, it mostly exists to make multi-env Terraform a bit less annoying. That said the integration isn't super tight, mostly by-design which does make it feel a bit clunky. If it were a product I would probably go with CloudFormation since it's much more scriptable, the "out of the box" experience would be a bit nicer.

**Comment by dcosson** [comment]
That makes sense, thanks for the great responses. I'm thinking I might be better off scripting something together from scratch, but Apex will definitely a great resource to help me figure out all the pieces that are required & useful.

Thanks!
