### ISSUE TITLE
Apex deploy not idempotent in either config or code

### ISSUE THREAD

**Issue by skabbes** [apex/apex#528]
Apex version 0.10.2
Apex platform: Go
Mac OSX Yosemite 10.10.5

When I try to `apex deploy` new versions of the code are _always_ deployed, the config is detected as if it has changed as well.  Even in back-to-back calls to `apex deploy` functions and configs are updated.  I also deployed 2 different versions, downloaded the zip files from the lambda UI and diffed the files - they did not differ.

** Info I am not sure whether it is relevant or not **
* I didn't notice this when I did the apex hello world example
* I do not have a function.json file
* ".go" files are apexignored
* I am running in a VPC
* I have 2 "instances" of apex running on my AWS account in order to isolate different IAM roles necessary
* I have added custom defined policies to my lambda role
* I have all of my lambda functions connected to CloudWatch events

**Project.json**
```json
{
  "name": "infra",
  "description": "This is a set of functions that will be used to manage infra",
  "runtime": "golang",
  "memory": 128,
  "timeout": 120,
  "role": "arn:aws:iam::AWS_ACCOUNT_ID:role/infra_lambda_function",
  "environment": {},
  "vpc": {
    "securityGroups": [
      "sg-SG1"
    ],
    "subnets": [
      "subnet-A",
      "subnet-B",
      "subnet-C"
    ]
  }
}
```

**.apexignore**
```
.*go
```

`apex deploy trigger_buildbot -l debug`
```text
   • loading functions in functions
   • loading function in functions/trigger_buildbot
   • deploying 1 functions    
   • deploying                 function=trigger_buildbot
   • creating build            function=trigger_buildbot
   • injecting prelude         function=trigger_buildbot
   • hook                      command=GOOS=linux GOARCH=amd64 go build -o main *.go function=trigger_buildbot hook=build
   • adding env                env=map[LAMBDA_FUNCTION_NAME:infra_trigger_buildbot APEX_FUNCTION_NAME:trigger_buildbot] function=trigger_buildbot
   • add shim                  function=trigger_buildbot
   • add file to zip           file=main function=trigger_buildbot
   • created build (2.6 MB)    function=trigger_buildbot
   • fetching config           function=trigger_buildbot
   • config changed            function=trigger_buildbot
   • updating config           function=trigger_buildbot
   • updating function         function=trigger_buildbot
   • updated alias current     function=trigger_buildbot version=20
   • function updated          function=trigger_buildbot name=infra_trigger_buildbot version=20
   • cleaning up version: 10   function=trigger_buildbot
   • cleaning 1 functions     
   • hook                      command=rm -f main function=trigger_buildbot hook=clean
   • conditional flush         above_duration=24h0m0s above_size=500 age=38m33.282169122s size=73
   • close     
```

I also notice this warning in Lambda:

<img width="1148" alt="screenshot 2016-08-17 00 31 16" src="https://cloud.githubusercontent.com/assets/592178/17728086/3ca9d676-6412-11e6-8657-30f9d321bc78.png">

**Comment by DavidTPate** [comment]
Yeah, I noticed the issue with Config changing causing a deployment of the code as well when I was going through and testing some things. It appears to be related to [this](https://github.com/apex/apex/blob/263e85b1e922e1398ad3c9078499dd50eea304bd/function/function.go#L248-L254) code block where having the config dirty also redeploys the code.

What happens is that it updates the configuration and then [Updates](https://github.com/apex/apex/blob/263e85b1e922e1398ad3c9078499dd50eea304bd/function/function.go#L297) the function. This update function blindly [deploys the function](https://github.com/apex/apex/blob/263e85b1e922e1398ad3c9078499dd50eea304bd/function/function.go#L342-L346) instead of checking the hash, which I think should be done instead via the [DeployCode](https://github.com/apex/apex/blob/263e85b1e922e1398ad3c9078499dd50eea304bd/function/function.go#L258) function so that the hash is checked. Following that it will then create/update the alias.

I'm not sure if there was a reason to have both "Update" and "DeployCode" with similar code for deploying a function, but hopefully @tj can shed some light on it if there was.

**Comment by skabbes** [comment]
Ah, that makes sense why the code keep being deployed - thanks. I believe the problems is that the canonical representation of the security groups and subnets on AWS doesn't respect the order in which apex sends them necessarily.

Although the type is an array, it really represents a set.  I'll take a stab at fixing this in a PR.  Thanks for the help!

https://github.com/apex/apex/blob/263e85b1e922e1398ad3c9078499dd50eea304bd/function/function.go#L748-L758
