### ISSUE TITLE
Mapping Apex Go Lambda to POST method with API Gateway

### ISSUE THREAD

**Issue by edasque** [apex/apex#565]
I was able to write a go function that takes the event as an input (a JSON object) and output a JSON object (by returning it).  If I invoke it with apex, it works flawlessly:
```Bash
apex invoke getEarningsCallDate_forTickerArrayConcurrent < event.json
{"AAPL":"27/10/2016","AMZN":"27/10/2016","AXP":"19/10/2016","DIS":"10/11/2016","EIGI":"7/11/2016","FB":"2/11/2016","GOOG":"27/10/2016","HAS":"17/10/2016","MSFT":"20/10/2016","NFLX":"17/10/2016","TSLA":"1/11/2016","XOM":"28/10/2016"}
```

A debug statement
```go
		log.Println("Event", res)
```
that prints the event JSON message, outputs:
```
/aws/lambda/earnings_getEarningsCallDate_forTickerArrayConcurrent 2016/10/04 19:37:21 Event {[AAPL XOM EIGI DIS HAS AMZN NFLX AXP GOOG FB TSLA MSFT]}
```
which is correct.

I mapped this lambda to an API gateway POST and when I invoke it with the JSON payload as the body, I see no event coming in, it shows up empty:

```
/aws/lambda/earnings_getEarningsCallDate_forTickerArrayConcurrent 2016/10/04 19:40:21 Event {[]}
```

What am I missing? If I test the Lambda on AWS with that same payload it works without an issue.

Cheers,

Erik
----

If you have a bug report please let us know the following:

  - __Operating system__: MacOS
  - __Apex Version__: 0.10.3

**Comment by DavidTPate** [comment]
So the core of the issue is just a lack of understanding of how API Gateway + Lambda works (not a bad thing).

The short answer is that you need to setup a mapping template to pass your Lambda function what it needs.

To do this, you'll need to go through the Lambda documentation and familiarize yourself with it.
* [Integrating API Gateway and Lambda](http://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-lambda.html)
* [Models and Mapping](http://docs.aws.amazon.com/apigateway/latest/developerguide/models-mappings.html)

**Comment by edasque** [comment]
Well, the problem was that I was using "Lambda Proxy integration" which doesn't ask for a mapping template. I need to run about why but once I checked that off, it worked.
