### ISSUE TITLE
Error: function build hook: sh: 1: source: not found

### ISSUE THREAD

**Issue by Enanodr** [apex/apex#589]
If you have a bug report please let us know the following:

  - __Operating system__: Ubuntu 15.10
  - __Apex Version__: 0.10.3

i ran : 
apex deploy resize-image --log-level debug
   • loading functions in functions
   • open                      env= function=resize-image
   • deploying 1 functions    
   • deploying                 env= function=resize-image
   • creating build            env= function=resize-image
   • hook                      command=source "$NVM_DIR/nvm.sh" && nvm exec npm install env= function=resize-image hook=build
   ⨯ Error: function resize-image: build hook: sh: 1: source: not found

Thanks for your time!

**Comment by tj** [comment]
Hmm at a glance it seems like `source` is missing, why I'm not sure haha, we do run with `sh` so it should be ok, curious if `. $NVM_DIR/nvm.sh` will work instead. Seems unrelated to apex though so I'll close for now, re-open if you find something else there!

**Comment by MatiasComercio** [comment]
If you are using Ubuntu (or other Linux distribution), apex have an issue: it heads all its files with `#!/bin/sh`, and that's why you may see the following error code when trying to execute some task (e.g.: apex deploy)

`Error: function build hook: sh: 1: source: not found`

This error is caused as `/bin/sh` is a link to `dash` system shell, i.e., `dash` system shell will be used instead of `bash` system shell.

If you have already installed apex, remove it (default location: `/usr/local/bin/apex`) and follow the below steps:

1. Replace the current link using `-f` to **force** the overwrite

   `$ sudo ln -sf bash /bin/sh`

2. [Install & update apex](http://apex.run/#installation)

3. Run the script you want, for example, `$ apex deploy`

4. If you want, restore your default system configuration

   `$ sudo ln -sf dash /bin/sh`

If you cannot manage to get it to work, just let me know.
