### ISSUE TITLE
Top-level function name support

### ISSUE THREAD

**Issue by pilwon** [apex/apex#73]
It'd be great if we can also deploy and manage top-level named lambda functions with `apex`.

(Example: `{{functionName}}` rather than `{{projectName}}_{{functionName}}`)

Use cases:
* want to ~~deploy~~ colocate all lambda functions (their source codes) in a single `apex` project repo
* want to have more control with the function names used

**Comment by tj** [comment]
Hmmm changing the template could cause collisions. For example later when we support deps properly you might have project A with `{{functionName}}` and project B with the same, then you're screwed. As far as "want to deploy all lambda functions from a single apex project" goes you can deploy them all with `apex deploy`, or did you mean something else?

**Comment by pilwon** [comment]
@tj I meant more about the way one organizes source code for lambda functions.

I personally prefer to use `apex` by setting up a separate repo dedicated for lambda deployments for all my projects (and their functions) deployable to a single AWS account. `apex` shim or pure `lambda` handlers would simply pass `event` and `context` to packages from other repos that have real logic. The benefit of this approach is `apex`-specific repo stays lightweight while the projects with actual logic are decoupled from `apex` or `lambda` as its primary deployment destination.

Namespacing with `{{projectName}}_{{functionName}}` is a perfect default to prevent name collisions and I support keeping this default unchanged. My suggestion is to add an additional option to drop `{{projectName}}_` prefixes.

**Comment by tj** [comment]
Ahh I see, maybe a more ideal thing would be to have nested projects for that. We don't have support yet but there's no reason you couldn't have multiple in one repo. The "master" project would just have the others as local deps. Any thoughts on that? I'm not against the function name thing but that seems like it would be more of a quick fix, if it doesn't have any other use-cases.

**Comment by pilwon** [comment]
@tj Being able to nest projects would be a quite useful project organization feature, however all functions having the same `{{masterProjectName}}_` prefix and no option to opt out from it seems somewhat limiting.

To elaborate on my second use case above, `apex`-deployed functions may not mix well with naming conventions adopted by existing or new functions managed outside `apex` (manually or via alternative tools). Instead of ruling everything with `apex`'s default, having an option to override the default either at project-level or function-level seems like the simplest solution to this problem. An alternative solution is allowing users to define a custom function name template in `project.json`. It's more powerful but also more complicated.

**Comment by tj** [comment]
Nesting would fix the original problem you mentioned, without any additional features. I know it's a tiny one, maybe not worth debating but arbitrary features snowball quickly. I guess the way I see it is if we build Apex right no one should really care what the resulting function names are. I think out of the options though I'd prefer the template in project.json since we'd need an ever stranger option in function.json like `prefix: false` or `lambdaName: "real-lambda-name"`.

**Comment by tmaiaroto** [comment]
Looking at what others have done...The node-lambda project also appends the environment/stage name to the function name. So if your directory reads "foo" it would deploy a "foo-production" ... I find this incredibly annoying.

Different situation, but same deal with the adjustment of function names. I would prefer prefixes/suffixes to be completely optional. So the same goes for prefixing the language (ie. `go_<functionName>`). I'd rather manage the names myself. I do care what the resulting function names are (and others may too if they were using something other than Apex before or are working with a team where others use different tools and such - it's unfair to assume Apex and Apex only always manages all of your Lambdas).

So yes, a `prefix:false` would be much appreciated, for me anyway. That may not need to be in `function.json` but perhaps `project.json`. I could see it strange and annoying to have to define for each function.

**Comment by tj** [comment]
Ah yeah I'm not a fan of that either, but more so just because I don't think mixing stages in a single AWS account is smart. I'm tempted to just remove the "name" field from function.json, if it differs from your directory name it would make me unhappy haha.

My vote then is for a name template which you just pass `""` to, and we'll send the Project and Function to the template. Not sure about the prop name, camel-case is meh but `nameTemplate` or similar.

Actually, later it may be useful to pass some user-specific information, especially for staging, then you could have `{{.User.Name}}_{{.Project.Name}}_{{.Function.Name}}`. I think I'm sold on that now

**Comment by tmaiaroto** [comment]
Sounds good to me. I just figured I'd chime in with my two cents and opinion from the perspective of working with others who will end up using their own tools to contribute Lambda functions. It's a shame AWS does not have more support here. It's more their problem.

Another idea might be to check for name conflicts on deploy?

**Comment by pilwon** [comment]
My vote for prop name is either `namePattern` or `nameTemplate`.

**Comment by tj** [comment]
Sounds good, thanks for the input!

**Comment by pilwon** [comment]
@tj On second thought, I think it'd be better to call this prop name `functionNameTemplate` to specify the final function name as the override target. I think some will get confused by thinking `nameTemplate` is for overriding the `{{.Project.Name}}` part because it is set in the `project.json` file and also `name` is a required prop of this configuration file.

**Comment by tj** [comment]
Yea maybe, super verbose but I guess that beats being confusing, I can't think of a nice terse name

**Comment by tj** [comment]
"role" and the others imply function-level for now as well, we might be better changing it to something like this later:

```json
{
  "name": "myproject",
  "functionDefaults": {
    "role": ...,
    "nameTemplate": ...
  }
}
```

**Comment by pilwon** [comment]
@tj Haha can't believe you dislike camelCase considering you are the living legend from the Node.js land. (I'm one of your biggest fans, btw) I can't think of a shorter name that's clear enough than `functionDefaults`. Should be a good start.

I think this `project.json` will eventually get fat as this project grows, and most of its content probably won't be relevant to `project` as much. Have you considered using the filename `apex.json` instead?

**Comment by tj** [comment]
Haha yea it could get pretty gross. We definitely need to think on that some more (re #59). I have mixed feelings but multiple config files may be nicer in a lot of cases than trying to shove them all in one. For example when we get to configuring API Gateway it may be nicer to just have `./gateways/*` instead of nesting in project.json.

That way we keep project.json to project level config/dependencies. Open to thoughts there though there's so many ways it could go.
