### ISSUE TITLE
Remove over-engineered runtime checks in plugins

### ISSUE THREAD

**Issue by tj** [apex/apex#731]
Like e5fff82ba2969169e13ca7d5f1c65f1f67b0456e, the others should be similar, right now it's annoying having to manually add versions.

**Comment by shelvinc** [comment]
I'm new to open source development in general but looking to contribute to this project. Would be willing to help on this with some assistance.

**Comment by ianrtracey** [comment]
@tj: To clarify on this, are you looking to make the runtime checks more generic (i.e. a check for only a certain prefix) rather than checking the list of specific version?

**Comment by tj** [comment]
@ianrtracey yup that's correct

**Comment by ianrtracey** [comment]
on it.

**Comment by ianrtracey** [comment]
Here's what I have so far: https://github.com/ianrtracey/apex/commit/d4c1b9807ed1c15907f8e284fab38bca45a49bfd

Couple of questions:
- Are the changes above what you had in mind?
- Should we abstract the plugin version checks to another module or config in order to avoid changing the finer logic for each language plugin?
- What default versions should the other languages infer to?

**Comment by tj** [comment]
@ianrtracey sweet LGTM! I think we're fine defaulting to the latest versions for the inference stuff
