### ISSUE TITLE
Lambda reserved variables error

### ISSUE THREAD

**Issue by stefanoeb** [apex/apex#829]
- __Operating system__: macOS High Sierra
  - __Apex Version__: 0.16.0

I am deploying functions with apex on lambda using a `--env-file` with some environment variables, the problem is that recently I'm getting an error in the `deploy` command:
```shell
Error: function xxx: InvalidParameterValueException: Lambda was unable to configure your environment variables because the environment variables you have provided contains reserved keys that are currently not supported for modification. Reserved keys used in this request: AWS_ACCESS_KEY
```

Well, clearly I'm sending sensitive data through `apex` and it's not a good practice ([since these keys are not encrypted during the deploy process](http://docs.aws.amazon.com/lambda/latest/dg/env_variables.html)). That said, I saw in some places that a good practice is using KMS to decrypt the variables on lambda.

I also saw this PR: https://github.com/apex/apex/pull/652
So now this is the only way to send AWS keys to lambda?

**Comment by maxbeatty** [comment]
How are you trying to use these AWS keys? 

If it's to call other AWS services, Lambda populates `AWS_ACCESS_KEY` etc. for the role you're using with the function (hence it's reserved).* For example if you're trying to publish to SNS from within your function, give your Lambda role that permissions and then you can use the AWS SDK within your function without any additional configuration because it will use the environment variables set by Lambda. Hope this helps!

_* This may not be 100% accurate as far as implementation but it's how you can think about the problem_

**Comment by stefanoeb** [comment]
Oh, you're right!

Just found this doc explaining all that is made available out of the box: http://docs.aws.amazon.com/lambda/latest/dg/current-supported-versions.html#lambda-environment-variables

Thanks for the clarification, and since there's no problem with apex itself this may be closed.

**Comment by vicary** [comment]
New document location: https://docs.aws.amazon.com/lambda/latest/dg/lambda-environment-variables.html
